### ISSUE TITLE
"Deleting local variable in strict mode" when using third part packages

### ISSUE THREAD

**Issue by nicolocarpignoli** [Chialab/rna-cli#5]
With some packages I sometimes encounter this error:

```
everything is fine with ESLint.
{ SyntaxError: Deleting local variable in strict mode (124:4) in /Users/nicolo/biblioteca-app/node_modules/snap-shot/node_modules/debug/src/node.js
    at error (/Users/nicolo/.config/yarn/global/node_modules/rollup/dist/rollup.js:169:15)
    at /Users/nicolo/.config/yarn/global/node_modules/rollup/dist/rollup.js:17413:17
    at <anonymous>
  pos: 3289,
  loc: Position { line: 124, column: 4 },
  raisedAt: 3306,
  code: 'PLUGIN_ERROR',
  plugin: 'commonjs',
  id: '/Users/nicolo/biblioteca-app/node_modules/snap-shot/node_modules/debug/src/node.js' }
```

In this case the package that cannot be used is: https://github.com/bahmutov/snap-shot

**Comment by edoardocavazza** [comment]
We should rethink the default for `strict` mode. Right now, it is disabled for all modules.
